clearlog.py c:\conf\jp-a-admin
clearlog.py c:\conf\jp-a-central
clearlog.py c:\conf\jp-a-front
clearlog.py c:\conf\jp-admin
clearlog.py c:\conf\jp-central
clearlog.py c:\conf\jp-front
clearlog.py c:\git_work\excelTester\target
clearlog.py c:\git_work\releaseRequest\target
clearlog.py c:\git_work\openApiStub
